version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,s3
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_ACCESS_KEY_ID=default
      - AWS_DEFAUTL_SECRET_KEY=default
      - LAMBDA_EXECUTOR=local
      - DATA_DIR="./.localstack/data"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./entrypoint.d/local-setup.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"